version: '3.8'

volumes:
  db_data:

services:
  frontend:  # TODO: Change
    build: ./path/to/your/reactjs/Dockerfile
    ports:
      - "8000:3000"
    depends_on:
      - springboot-backend
      - fastapi-backend

  springboot-backend:
    build:
      dockerfile: ./iwcd-lct2023-backend/Dockerfile
      context: ./iwcd-lct2023-backend
    ports:
      - "8001:8080"
    depends_on:
      - db
      - fastapi-backend

  fastapi-backend:
    build:
      dockerfile: ./ML/Dockerfile
      context: ./ML/model
    volumes:
      - "./ml-models/gazprom_model:/model/app/models:ro"
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: ./.env
    volumes:
      - "db_data:/var/lib/postgresql/data"
