version: '3.8'

volumes:
  postgres_data:

services:
  frontend:  # TODO: Change
    build: ./path/to/your/reactjs/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - springboot-backend
      - fastapi-backend

  springboot-backend:
    build:
      dockerfile: ./iwcd-lct2023-backend/Dockerfile
      context: ./iwcd-lct2023-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - fastapi-backend

  fastapi-backend:
    build:
      dockerfile: ./ML/Dockerfile
      context: ./ML/model
    ports:
      - "3333:3333"  # Check proper port number
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "15432:5432"
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
