export enum FetchMainAction {
	FETCH_MAIN_REQUEST = 'FETCH_MAIN_REQUEST',
	FETCH_MAIN_SUCCESS = 'FETCH_MAIN_SUCCESS',
	FETCH_MAIN_FAILURE = 'FETCH_MAIN_FAILURE',
}

export enum MainAction {
	SET_MAIN_DATA = 'SET_MAIN_DATA',
}

export enum FetchRequestsAction {
	FETCH_REQUESTS_REQUEST = 'FETCH_REQUESTS_REQUEST',
	FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS',
	FETCH_REQUESTS_FAILURE = 'FETCH_REQUESTS_FAILURE',
}

export enum RequestsAction {
	SET_REQUESTS_DATA = 'SET_REQUESTS_DATA',
}

export enum FetchAuthAction {
	FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST',
	FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS',
	FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE',
}

export enum AuthAction {
	SET_AUTH_DATA = 'SET_AUTH_DATA',
}
